#### LINUX TARGETS ####

[target.x86_64-unknown-linux-gnu]
image = "spacekookie/fool:linux_x86_64"

[target.i686-unknown-linux-gnu]
image = "spacekookie/fool:linux_i686"

#### FREEBSD TARGETS ####

[target.x86_64-unknown-freebsd]
image = "spacekookie/fool:freebsd_x86_64"

[target.i686-unknown-freebsd]
image = "spacekookie/fool:freebsd_i686"